[package]
name = "bot"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
shakmaty = { git = "https://github.com/niklasf/shakmaty" }
vampirc-uci = {version = "0.11" }
nn = { path = "../nn" }

[profile.release]
debug = true
