name: Deploy to Lichess

on:
  push:
    branches:
      - master
      - lichess-bot

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build bot
        run: cargo build --release
        working-directory: bot
        env:
          RUSTFLAGS: "-C target-feature=+sse3,+avx,+avx2"

      - name: Fill in Lichess token
        run: sed "s/LICHESS_TOKEN/${{ secrets.LICHESS_TOKEN }}/g" config.yml.template > config.yml
        working-directory: bot/.github/workflows

      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          source: "bot/bot/target/release/bot,bot/.github/workflows/config.yml"
          target: "/root/lichess-bot"
