name: Deploy to Lichess

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build bot
        run: cargo build --release
        working-directory: bot
        env:
          RUSTFLAGS: "-C target-feature=+sse,+sse2,+ssse3,+sse4.1,+sse4.2,+avx,+avx2"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: mlomb/thesisbot:latest
